public class MethodOverLoading {
    public void add(Integer a,Integer b){
        
    }
    public void add(Decimal a,Integer b){
        
    }
    public void add(Integer a,Decimal b){
        
    }
    /*public Integer add(Decimal a,Integer b){   //return type different but same datatype not allowed
        return b;
    }*/
    public void add(Integer a,Integer b,Integer c){
        
    }
    public void add(Integer a,Integer b,Integer c,Integer d){
        
    }
}